---
- hosts: localhost
  connection: local
  tasks:
    - name: RPMfusion installed
      dnf:
        name: '{{ item }}'
        state: present
      become: yes
      with_items:
        - 'http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm'
        - 'http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm'
    - name: development tools installed
      dnf:
        name: '{{ item }}'
        state: present
      become: yes
      with_items:
        - "@Development tools"
        - python-devel
        - python3-devel
        - redhat-rpm-config
        - jq
        - the_silver_searcher
        - parcellite
        - dropbox
        - nautilus-dropbox
        - hg
        - tmux
        - vim
        - ansible
        - python2-dnf
        - kernel-devel
        - kmod-VirtualBox
        - vagrant
        - zlib-devel
        - bzip2-devel
        - openssl-devel
        - readline-devel
        - ncurses-devel
        - sqlite-devel
        - gdbm-devel
        - db4-devel
        - expat-devel
        - libpcap-devel
        - xz-devel
        - pcre-devel
        - libffi-devel
        - openssl-devel
        - mariadb
        - mariadb-server
