---
- hosts: localhost
  connection: local
  tasks:
    - name: RPMfusion installed
      dnf:
        name: '{{ item }}'
        state: present
      become: yes
      with_items:
        - 'http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm'
        - 'http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm'
    - name: nodejs repo installed
      dnf:
        name: 'https://rpm.nodesource.com/pub_6.x/fc/24/x86_64/nodesource-release-fc{{ ansible_distribution_major_version }}-1.noarch.rpm'
        state: present
      become: yes
    - name: development tools installed
      dnf:
        name: '{{ item }}'
        state: present
      become: yes
      with_items:
        - "@Development tools"
        - gcc-c++
        - python-devel
        - python3-devel
        - ruby
        - redhat-rpm-config
        - jq
        - the_silver_searcher
        - parcellite
        - dropbox
        - nautilus-dropbox
        - hg
        - tmux
        - vim
        - ansible
        - python2-dnf
        - kernel-devel
        - kmod-VirtualBox
        - vagrant
        - zlib-devel
        - bzip2-devel
        - openssl-devel
        - readline-devel
        - ncurses-devel
        - sqlite-devel
        - gdbm-devel
        - db4-devel
        - expat-devel
        - libpcap-devel
        - xz-devel
        - pcre-devel
        - libffi-devel
        - openssl-devel
        - mariadb
        - mariadb-devel
        - mariadb-server
        - php
        - php-pear
        - php-pgsql
        - pandoc
        - htop
        - remmina
        - aspell
        - aspell-en
        - aspell-es
        # pillow
        - libtiff-devel
        - libjpeg-devel
        - zlib-devel
        - freetype-devel
        - lcms2-devel
        - libwebp-devel
        - tcl-devel
        - tk-devel
        - xorg-x11-server-Xvfb
        - exfat-utils
        - fuse-exfat
        - zeal
        - liboping
        - translate-toolkit
        - byzanz
